# 상품을 구매한 회원 비율 구하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131534
# 작성자: 손삼주
# 작성일: 2026. 03. 12. 15:45:36

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT a.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT a.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE s 
    LEFT JOIN
    (
    SELECT USER_ID
	FROM USER_INFO
	WHERE YEAR(JOINED) = 2021
    ) a 
    ON s.USER_ID = a.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
