# 오프라인/온라인 판매 데이터 통합하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131537
# 작성자: 손삼주
# 작성일: 2026. 01. 21. 11:29:17

-- 코드를 입력하세요
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM(
SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM ONLINE_SALE
UNION ALL
SELECT OFFLINE_SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE
) AS TOTAL_TABLE
WHERE SALES_DATE LIKE ('%2022-03%')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID