# 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/151139
# 작성자: 손삼주
# 작성일: 2026. 02. 26. 11:01:56

-- 코드를 입력하세요 CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- RECORDS
SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE 1
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >=5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC

